dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    packages:
    - libboost-test-dev
    - doxygen
    - graphviz

script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
- doxygen Doxyfile

deploy:
  - provider: script
    skip_cleanup: true
    script:
    - curl -T packet-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ujacksonrr3:$BINTRAY_API_KEY "https://api.bintray.com/content/jacksonrr3/otus-cpp/homework/$TRAVIS_BUILD_NUMBER/packet-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"

  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
     branch: master
