# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/cmake-3.12.4/bin/cmake

# The command to remove a file.
RM = /usr/local/cmake-3.12.4/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/travis/build/jacksonrr3/packet

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/travis/build/jacksonrr3/packet

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/local/cmake-3.12.4/bin/cpack --config ./CPackSourceConfig.cmake /home/travis/build/jacksonrr3/packet/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/local/cmake-3.12.4/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/cmake-3.12.4/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/cmake-3.12.4/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/cmake-3.12.4/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/cmake-3.12.4/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/cmake-3.12.4/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/cmake-3.12.4/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/cmake-3.12.4/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/cmake-3.12.4/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/cmake-3.12.4/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/travis/build/jacksonrr3/packet/CMakeFiles /home/travis/build/jacksonrr3/packet/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/travis/build/jacksonrr3/packet/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named packet_lib

# Build rule for target.
packet_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 packet_lib
.PHONY : packet_lib

# fast build rule for target.
packet_lib/fast:
	$(MAKE) -f CMakeFiles/packet_lib.dir/build.make CMakeFiles/packet_lib.dir/build
.PHONY : packet_lib/fast

#=============================================================================
# Target rules for targets named test_packet

# Build rule for target.
test_packet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_packet
.PHONY : test_packet

# fast build rule for target.
test_packet/fast:
	$(MAKE) -f CMakeFiles/test_packet.dir/build.make CMakeFiles/test_packet.dir/build
.PHONY : test_packet/fast

src/other.o: src/other.cpp.o

.PHONY : src/other.o

# target to build an object file
src/other.cpp.o:
	$(MAKE) -f CMakeFiles/packet_lib.dir/build.make CMakeFiles/packet_lib.dir/src/other.cpp.o
.PHONY : src/other.cpp.o

src/other.i: src/other.cpp.i

.PHONY : src/other.i

# target to preprocess a source file
src/other.cpp.i:
	$(MAKE) -f CMakeFiles/packet_lib.dir/build.make CMakeFiles/packet_lib.dir/src/other.cpp.i
.PHONY : src/other.cpp.i

src/other.s: src/other.cpp.s

.PHONY : src/other.s

# target to generate assembly for a file
src/other.cpp.s:
	$(MAKE) -f CMakeFiles/packet_lib.dir/build.make CMakeFiles/packet_lib.dir/src/other.cpp.s
.PHONY : src/other.cpp.s

src/packet.o: src/packet.cpp.o

.PHONY : src/packet.o

# target to build an object file
src/packet.cpp.o:
	$(MAKE) -f CMakeFiles/packet_lib.dir/build.make CMakeFiles/packet_lib.dir/src/packet.cpp.o
.PHONY : src/packet.cpp.o

src/packet.i: src/packet.cpp.i

.PHONY : src/packet.i

# target to preprocess a source file
src/packet.cpp.i:
	$(MAKE) -f CMakeFiles/packet_lib.dir/build.make CMakeFiles/packet_lib.dir/src/packet.cpp.i
.PHONY : src/packet.cpp.i

src/packet.s: src/packet.cpp.s

.PHONY : src/packet.s

# target to generate assembly for a file
src/packet.cpp.s:
	$(MAKE) -f CMakeFiles/packet_lib.dir/build.make CMakeFiles/packet_lib.dir/src/packet.cpp.s
.PHONY : src/packet.cpp.s

src/protocol.o: src/protocol.cpp.o

.PHONY : src/protocol.o

# target to build an object file
src/protocol.cpp.o:
	$(MAKE) -f CMakeFiles/packet_lib.dir/build.make CMakeFiles/packet_lib.dir/src/protocol.cpp.o
.PHONY : src/protocol.cpp.o

src/protocol.i: src/protocol.cpp.i

.PHONY : src/protocol.i

# target to preprocess a source file
src/protocol.cpp.i:
	$(MAKE) -f CMakeFiles/packet_lib.dir/build.make CMakeFiles/packet_lib.dir/src/protocol.cpp.i
.PHONY : src/protocol.cpp.i

src/protocol.s: src/protocol.cpp.s

.PHONY : src/protocol.s

# target to generate assembly for a file
src/protocol.cpp.s:
	$(MAKE) -f CMakeFiles/packet_lib.dir/build.make CMakeFiles/packet_lib.dir/src/protocol.cpp.s
.PHONY : src/protocol.cpp.s

src/test_packet.o: src/test_packet.cpp.o

.PHONY : src/test_packet.o

# target to build an object file
src/test_packet.cpp.o:
	$(MAKE) -f CMakeFiles/test_packet.dir/build.make CMakeFiles/test_packet.dir/src/test_packet.cpp.o
.PHONY : src/test_packet.cpp.o

src/test_packet.i: src/test_packet.cpp.i

.PHONY : src/test_packet.i

# target to preprocess a source file
src/test_packet.cpp.i:
	$(MAKE) -f CMakeFiles/test_packet.dir/build.make CMakeFiles/test_packet.dir/src/test_packet.cpp.i
.PHONY : src/test_packet.cpp.i

src/test_packet.s: src/test_packet.cpp.s

.PHONY : src/test_packet.s

# target to generate assembly for a file
src/test_packet.cpp.s:
	$(MAKE) -f CMakeFiles/test_packet.dir/build.make CMakeFiles/test_packet.dir/src/test_packet.cpp.s
.PHONY : src/test_packet.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... package_source"
	@echo "... package"
	@echo "... packet_lib"
	@echo "... test"
	@echo "... edit_cache"
	@echo "... test_packet"
	@echo "... rebuild_cache"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... install/local"
	@echo "... src/other.o"
	@echo "... src/other.i"
	@echo "... src/other.s"
	@echo "... src/packet.o"
	@echo "... src/packet.i"
	@echo "... src/packet.s"
	@echo "... src/protocol.o"
	@echo "... src/protocol.i"
	@echo "... src/protocol.s"
	@echo "... src/test_packet.o"
	@echo "... src/test_packet.i"
	@echo "... src/test_packet.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

